env:
  browser: true
  es2021: true
extends:
  - love
  - standard-jsx
  - standard-react
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
root: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-refresh
  - '@typescript-eslint'
rules:
  react/prop-types: off
  react/react-in-jsx-scope: off
  '@typescript-eslint/non-nullable-type-assertion-style': off
  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true
ignorePatterns:
  - dist
  - '*.config.ts'